const aryMovies = [
    'The Dark Knight',
    'The Return of the King',
    'Gladiator',
    'The Departed',
    'No Country for Old Men',
    'Memento',
    'Up',
    'Inglorious Basterds',
    'Kill Bill Vol 1',
    'There Will Be Blood',
    'Eternal Sunshine Of The Spotless Mind',
    'Casino Royale',
    'Pans Labyrinth',
    'Children Of Men',
    'Donnie Darko',
    '28 Days Later',
    'American Psycho',
    'City Of God',
    'Zodiac',
    'Almost Famous'
]